import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  UserOutline,
  TeamOutline,
  FileTextOutline,
  AppstoreOutline,
  SolutionOutline,
  LogoutOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  InfoCircleOutline,
  HomeOutline,
  PieChartOutline,
  MailOutline,
  PhoneOutline,
  ArrowRightOutline,
  ProjectOutline,
  DownOutline,
  BarChartOutline,
  SearchOutline, FileDoneOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  UserOutline,
  TeamOutline,
  FileTextOutline,
  AppstoreOutline,
  SolutionOutline,
  LogoutOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  InfoCircleOutline,
  HomeOutline,
  PieChartOutline,
  MailOutline,
  PhoneOutline,
  ArrowRightOutline,
  ProjectOutline,
  DownOutline,
  BarChartOutline,
  SearchOutline,
  FileDoneOutline
];
